# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime')),
                ('subtitle', models.TextField(verbose_name='subtitle')),
                ('text', models.TextField(verbose_name='text')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('visitors', models.IntegerField(blank=True, default=0, null=True, verbose_name='visitors')),
                ('youtube_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='youtube_link')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review', verbose_name='image')),
                ('cover', models.BooleanField(default=False, verbose_name='cover')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_images', to='reviews.Review')),
            ],
        ),
    ]
