# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='review',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='review',
            name='visitors',
        ),
        migrations.RemoveField(
            model_name='review',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='review',
            name='reward',
            field=models.FloatField(blank=True, null=True, verbose_name='reward'),
        ),
        migrations.AddField(
            model_name='review',
            name='source_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='source id'),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('payout', 'payout')], max_length=255, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='review',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_reviews', to='reviews.Asset'),
        ),
    ]
