# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20171118_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='votes'),
        ),
    ]
