# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='publish'),
        ),
    ]
