# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20171118_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='complete'),
        ),
    ]
