# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='golos_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='golos user'),
        ),
    ]
