# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_golos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='btc',
            field=models.FloatField(blank=True, null=True, verbose_name='BTC'),
        ),
        migrations.AddField(
            model_name='review',
            name='rub',
            field=models.FloatField(blank=True, null=True, verbose_name='RUB'),
        ),
    ]
