# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20171118_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, verbose_name='slug'),
        ),
    ]
